package com.example.androiddevchallenge.stubdata

import androidx.annotation.DrawableRes
import com.example.androiddevchallenge.R

data class ForecastData(
    @DrawableRes
    val image: Int,
    val temp: Int,
    val time: String,
    val type: ForecastType = ForecastType.TEMPERATURE,
    val contentDescription: String = ""
)

enum class ForecastType {
    TEMPERATURE,
    SUNRISE,
    SUNSET
}

val minneapolisHourlyDetails = listOf(
    ForecastData(R.drawable.ic_sun,10,"Now",contentDescription = "Sunny"),
    ForecastData(R.drawable.ic_sun,10,"3 PM",contentDescription = "Sunny"),
    ForecastData(R.drawable.ic_sun,10,"4 PM",contentDescription = "Sunny"),
    ForecastData(R.drawable.ic_sun,10,"5 PM",contentDescription = "Sunny"),
    ForecastData(R.drawable.ic_sun,8,"6 PM",contentDescription = "Sunny"),
    ForecastData(R.drawable.ic_sun,7,"7 PM",contentDescription = "Sunny"),
    ForecastData(R.drawable.ic_sunset,0,"7:23 PM", type = ForecastType.SUNSET),
    ForecastData(R.drawable.ic_moon,6,"8 PM",contentDescription = "Clear"),
    ForecastData(R.drawable.ic_moon,4,"9 PM",contentDescription = "Clear"),
    ForecastData(R.drawable.ic_moon,3,"10 PM",contentDescription = "Clear"),
    ForecastData(R.drawable.ic_moon,2,"11 PM",contentDescription = "Clear"),
    ForecastData(R.drawable.ic_moon,1,"12 AM",contentDescription = "Clear"),
    ForecastData(R.drawable.ic_moon,0,"1 AM",contentDescription = "Clear"),
    ForecastData(R.drawable.ic_moon,0,"2 PM",contentDescription = "Clear"),
    ForecastData(R.drawable.ic_moon,-1,"3 AM",contentDescription = "Clear"),
    ForecastData(R.drawable.ic_moon,-1,"4 AM",contentDescription = "Clear"),
    ForecastData(R.drawable.ic_moon,-2,"5 AM",contentDescription = "Clear"),
    ForecastData(R.drawable.ic_moon,-2,"6 AM",contentDescription = "Clear"),
    ForecastData(R.drawable.ic_moon,-2,"7 AM",contentDescription = "Clear"),
    ForecastData(R.drawable.ic_sunrise,0,"7:17 AM", type = ForecastType.SUNRISE),
    ForecastData(R.drawable.ic_sun,-2,"8 AM",contentDescription = "Sunny"),
    ForecastData(R.drawable.ic_sun,-1,"9 AM",contentDescription = "Sunny"),
    ForecastData(R.drawable.ic_sun,2,"10 AM",contentDescription = "Sunny"),
    ForecastData(R.drawable.ic_sun,4,"11 AM",contentDescription = "Sunny"),
    ForecastData(R.drawable.ic_sun,6,"12 PM",contentDescription = "Sunny"),
    ForecastData(R.drawable.ic_sun,8,"1 PM",contentDescription = "Sunny"),
    ForecastData(R.drawable.ic_sun,9,"2 PM",contentDescription = "Sunny")
)

val fairbanksHourlyDetails = listOf(
    ForecastData(R.drawable.ic_sun_cloud,-13,"Now",contentDescription = "Partly Cloudy"),
    ForecastData(R.drawable.ic_sun_cloud,-12,"12 PM",contentDescription = "Partly Cloudy"),
    ForecastData(R.drawable.ic_sun_cloud,-12,"1 PM",contentDescription = "Partly Cloudy"),
    ForecastData(R.drawable.ic_sun_cloud,-11,"2 PM",contentDescription = "Partly Cloudy"),
    ForecastData(R.drawable.ic_sun_cloud,-12,"3 PM",contentDescription = "Partly Cloudy"),
    ForecastData(R.drawable.ic_sun_cloud,-12,"4 PM",contentDescription = "Partly Cloudy"),
    ForecastData(R.drawable.ic_sun,-15,"5 PM",contentDescription = "Sunny"),
    ForecastData(R.drawable.ic_sun,-17,"6 PM",contentDescription = "Sunny"),
    ForecastData(R.drawable.ic_sun,-18,"7 PM",contentDescription = "Sunny"),
    ForecastData(R.drawable.ic_sun,-19,"8 PM",contentDescription = "Sunny"),
    ForecastData(R.drawable.ic_sunset,0,"8:05 PM", type = ForecastType.SUNSET),
    ForecastData(R.drawable.ic_moon,-17,"9 PM",contentDescription = "Clear"),
    ForecastData(R.drawable.ic_moon,-18,"10 PM",contentDescription = "Clear"),
    ForecastData(R.drawable.ic_moon,-19,"11 PM",contentDescription = "Clear"),
    ForecastData(R.drawable.ic_moon,-20,"12 AM",contentDescription = "Clear"),
    ForecastData(R.drawable.ic_moon,-21,"1 AM",contentDescription = "Clear"),
    ForecastData(R.drawable.ic_moon,-21,"2 AM",contentDescription = "Clear"),
    ForecastData(R.drawable.ic_moon,-22,"3 AM",contentDescription = "Clear"),
    ForecastData(R.drawable.ic_moon,-22,"4 AM",contentDescription = "Clear"),
    ForecastData(R.drawable.ic_moon,-22,"5 AM",contentDescription = "Clear"),
    ForecastData(R.drawable.ic_moon,-23,"6 AM",contentDescription = "Clear"),
    ForecastData(R.drawable.ic_moon,-23,"7 AM",contentDescription = "Clear"),
    ForecastData(R.drawable.ic_sunrise,0,"7:49 AM", type = ForecastType.SUNRISE),
    ForecastData(R.drawable.ic_sun,-23,"8 AM",contentDescription = "Sunny"),
    ForecastData(R.drawable.ic_sun,-22,"9 AM",contentDescription = "Sunny"),
    ForecastData(R.drawable.ic_sun,-20,"10 AM",contentDescription = "Sunny"),
    ForecastData(R.drawable.ic_sun,-17,"11 AM",contentDescription = "Sunny"),
)

val munichHourlyDetails = listOf(
    ForecastData(R.drawable.ic_snow,0,"Now",contentDescription = "Snow Shower"),
    ForecastData(R.drawable.ic_snow,0,"9 PM",contentDescription = "Snow Shower"),
    ForecastData(R.drawable.ic_cloud,-1,"10 PM",contentDescription = "Cloudy"),
    ForecastData(R.drawable.ic_cloud,-1,"11 PM",contentDescription = "Cloudy"),
    ForecastData(R.drawable.ic_cloud,-2,"12 AM",contentDescription = "Cloudy"),
    ForecastData(R.drawable.ic_cloud,-2,"1 AM",contentDescription = "Cloudy"),
    ForecastData(R.drawable.ic_cloud,-3,"2 AM",contentDescription = "Cloudy"),
    ForecastData(R.drawable.ic_snow,-3,"3 AM",contentDescription = "Snow Shower"),
    ForecastData(R.drawable.ic_snow,-3,"4 AM",contentDescription = "Snow Shower"),
    ForecastData(R.drawable.ic_snow,-4,"5 AM",contentDescription = "Snow Shower"),
    ForecastData(R.drawable.ic_snow,-4,"6 AM",contentDescription = "Snow Shower"),
    ForecastData(R.drawable.ic_sunset,0,"6:16 AM", type = ForecastType.SUNRISE),
    ForecastData(R.drawable.ic_snow,-3,"7 AM",contentDescription = "Snow Shower"),
    ForecastData(R.drawable.ic_snow,-3,"8 PM",contentDescription = "Snow Shower"),
    ForecastData(R.drawable.ic_snow,-3,"9 AM",contentDescription = "Snow Shower"),
    ForecastData(R.drawable.ic_snow,-2,"10 AM",contentDescription = "Snow Shower"),
    ForecastData(R.drawable.ic_snow,-1,"11 AM",contentDescription = "Snow Shower"),
    ForecastData(R.drawable.ic_cloud,-1,"12 PM",contentDescription = "Cloudy"),
    ForecastData(R.drawable.ic_cloud,0,"1 PM",contentDescription = "Cloudy"),
    ForecastData(R.drawable.ic_cloud,0,"2 PM",contentDescription = "Cloudy"),
    ForecastData(R.drawable.ic_cloud,0,"3 PM",contentDescription = "Cloudy"),
    ForecastData(R.drawable.ic_cloud,0,"4 PM",contentDescription = "Cloudy"),
    ForecastData(R.drawable.ic_cloud,0,"5 PM",contentDescription = "Cloudy"),
    ForecastData(R.drawable.ic_sun_cloud,-1,"6 PM",contentDescription = "Partly Cloudy"),
    ForecastData(R.drawable.ic_sunset,0,"6:26 PM", type = ForecastType.SUNSET),
    ForecastData(R.drawable.ic_moon_cloud,-2,"7 PM",contentDescription = "Party Cloudy"),
    ForecastData(R.drawable.ic_moon_cloud,-2,"8 PM",contentDescription = "Party Cloudy")
)

val seattleHourlyDetails = listOf(
    ForecastData(R.drawable.ic_cloud,11,"Now",contentDescription = "Cloudy"),
    ForecastData(R.drawable.ic_cloud,12,"1 PM",contentDescription = "Cloudy"),
    ForecastData(R.drawable.ic_cloud,12,"2 PM",contentDescription = "Cloudy"),
    ForecastData(R.drawable.ic_cloud,12,"3 PM",contentDescription = "Cloudy"),
    ForecastData(R.drawable.ic_cloud,11,"4 PM",contentDescription = "Cloudy"),
    ForecastData(R.drawable.ic_rain_cloud,11,"5 PM",contentDescription = "Drizzle"),
    ForecastData(R.drawable.ic_rain_cloud,9,"6 PM",contentDescription = "Drizzle"),
    ForecastData(R.drawable.ic_rain_cloud,9,"7 PM",contentDescription = "Drizzle"),
    ForecastData(R.drawable.ic_sunset,0,"7:21 PM", type = ForecastType.SUNSET),
    ForecastData(R.drawable.ic_rain_cloud,9,"8 PM",contentDescription = "Drizzle"),
    ForecastData(R.drawable.ic_rain_cloud,9,"9 PM",contentDescription = "Drizzle"),
    ForecastData(R.drawable.ic_rain_cloud,8,"10 PM",contentDescription = "Drizzle"),
    ForecastData(R.drawable.ic_rain_cloud,8,"11 PM",contentDescription = "Drizzle"),
    ForecastData(R.drawable.ic_rain_cloud,8,"12 AM",contentDescription = "Drizzle"),
    ForecastData(R.drawable.ic_rain_cloud,8,"1 AM",contentDescription = "Drizzle"),
    ForecastData(R.drawable.ic_rain_cloud,8,"2 AM",contentDescription = "Drizzle"),
    ForecastData(R.drawable.ic_rain_cloud,7,"3 AM",contentDescription = "Drizzle"),
    ForecastData(R.drawable.ic_rain_cloud,7,"4 AM",contentDescription = "Drizzle"),
    ForecastData(R.drawable.ic_rain_cloud,7,"5 AM",contentDescription = "Drizzle"),
    ForecastData(R.drawable.ic_rain_cloud,7,"6 AM",contentDescription = "Drizzle"),
    ForecastData(R.drawable.ic_rain_cloud,7,"7 AM",contentDescription = "Drizzle"),
    ForecastData(R.drawable.ic_sunset,0,"7:11 AM", type = ForecastType.SUNRISE),
    ForecastData(R.drawable.ic_rain_cloud,6,"8 AM",contentDescription = "Drizzle"),
    ForecastData(R.drawable.ic_rain_cloud,7,"9 AM",contentDescription = "Drizzle"),
    ForecastData(R.drawable.ic_rain_cloud,7,"10 AM",contentDescription = "Drizzle"),
    ForecastData(R.drawable.ic_rain_cloud,8,"11 AM",contentDescription = "Drizzle"),
    ForecastData(R.drawable.ic_cloud,9,"12 PM",contentDescription = "Cloudy")
)

val yarroweyahHourlyDetails = listOf(
    ForecastData(R.drawable.ic_moon,14,"Now",contentDescription = "Clear"),
    ForecastData(R.drawable.ic_moon,15,"7 AM",contentDescription = "Clear"),
    ForecastData(R.drawable.ic_sunset,0,"7:20 AM", type = ForecastType.SUNRISE),
    ForecastData(R.drawable.ic_sun_cloud,16,"8 AM",contentDescription = "Partly Cloudy"),
    ForecastData(R.drawable.ic_sun_cloud,19,"9 AM",contentDescription = "Partly Cloudy"),
    ForecastData(R.drawable.ic_sun_cloud,22,"10 AM",contentDescription = "Partly Cloudy"),
    ForecastData(R.drawable.ic_sun_cloud,24,"11 AM",contentDescription = "Partly Cloudy"),
    ForecastData(R.drawable.ic_cloud,26,"12 PM",contentDescription = "Cloudy"),
    ForecastData(R.drawable.ic_cloud,27,"1 PM",contentDescription = "Cloudy"),
    ForecastData(R.drawable.ic_cloud,27,"2 PM",contentDescription = "Cloudy"),
    ForecastData(R.drawable.ic_cloud,27,"3 PM",contentDescription = "Cloudy"),
    ForecastData(R.drawable.ic_cloud,27,"4 PM",contentDescription = "Cloudy"),
    ForecastData(R.drawable.ic_cloud,27,"5 PM",contentDescription = "Cloudy"),
    ForecastData(R.drawable.ic_cloud,26,"6 PM",contentDescription = "Cloudy"),
    ForecastData(R.drawable.ic_cloud,24,"7 PM",contentDescription = "Cloudy"),
    ForecastData(R.drawable.ic_sunset,0,"7:29 PM", type = ForecastType.SUNSET),
    ForecastData(R.drawable.ic_rain_cloud,22,"8 PM",contentDescription = "Rainy"),
    ForecastData(R.drawable.ic_rain_cloud,21,"9 PM",contentDescription = "Rainy"),
    ForecastData(R.drawable.ic_rain_cloud,20,"10 PM",contentDescription = "Rainy"),
    ForecastData(R.drawable.ic_rain_cloud,19,"11 PM",contentDescription = "Rainy"),
    ForecastData(R.drawable.ic_rain_cloud,19,"12 AM",contentDescription = "Rainy"),
    ForecastData(R.drawable.ic_rain_cloud,18,"1 AM",contentDescription = "Rainy"),
    ForecastData(R.drawable.ic_rain_cloud,18,"2 AM",contentDescription = "Rainy"),
    ForecastData(R.drawable.ic_rain_cloud,18,"3 AM",contentDescription = "Rainy"),
    ForecastData(R.drawable.ic_rain_cloud,18,"4 AM",contentDescription = "Rainy"),
    ForecastData(R.drawable.ic_rain_cloud,17,"5 AM",contentDescription = "Rainy"),
    ForecastData(R.drawable.ic_rain_cloud,17,"6 PM",contentDescription = "Rainy")
)
